# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ]; #
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; #
  boot.extraModulePackages = [ ]; #

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb4307b8-137c-4390-84a8-8998debb9d0a";
      fsType = "ext4";
    }; #
  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/4BD9-6B1F";
      fsType = "vfat";
    }; #
  swapDevices =
    [ { device = "/dev/disk/by-uuid/17593cf3-5037-43bb-8753-e4bd2ecdf889"; }
    ]; #

  networking.useDHCP = lib.mkDefault true; #

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; #
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave"; #
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; #
}
